version: 0.0
os: linux
files:
  - source: /
    destination: /home/kyle/kyleuniversities
permissions:
  - object: /home/kyle
    owner: kyle
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: scripts/reload-pm2.sh
      timeout: 300
